# Numpy Library

In [1]:
# numpy Library
# numeric Library (Numerical in Python)
# importing numpy
import numpy as np

In [2]:
# Creating An Anrray
# array , arange , linspace

In [3]:
li = [2,3,4,5,6]
li

[2, 3, 4, 5, 6]

In [4]:
# Creating An Anrray
# array , arange , linspace
ar = np.array([2,3,4,5,6])
ar

array([2, 3, 4, 5, 6])

In [5]:
li = [2,3,4,"aman",4.0,True]
li

[2, 3, 4, 'aman', 4.0, True]

In [9]:
ar = np.array([2,3,4,"aman",4.0,True])
ar

array(['2', '3', '4', 'aman', '4.0', 'True'], dtype='<U32')

In [10]:
# arange
ar = np.arange(1,20,2)
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
ar = np.arange(1,100,1)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
# linspace        (same space are two number)
ar = np.linspace(0.5,5,10)         # first number or second end number and how many number between in two number
ar


array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
ar = np.linspace(1,10,100)
ar

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [20]:
# Dimension
# Zero Dimension Array

ar = np.array(10)
ar , np.ndim(ar) , np.shape(ar) ,ar

(array(10), 0, (), array(10))

In [4]:
# One dimension Array
import numpy as np
ar = np.array([2,3,4,5,5])
ar , np.ndim(ar) , np.shape(ar)

(array([2, 3, 4, 5, 5]), 1, (5,))

# Second Day 

In [5]:
# Some mehtods in 
# Sum
# Max
# Min
# len                         (This is build-in-method)


In [16]:
import numpy as np
ar = np.array([1,2,3,4,5,6,7,8,9,10])
sum(ar)


np.int64(55)

In [17]:
min(ar)


np.int64(1)

In [18]:
max(ar)


np.int64(10)

In [19]:
len(ar)                               

10

In [4]:
# Now we a create methods user by
# max 
# min
import numpy as np
ar1 = np.array([1,2,3,4,5,6,7,8,9,10])
maxs = ar1[0]
for a in ar1:
    if(a>maxs):
        maxs = a
maxs

np.int64(10)

In [5]:
maxs

np.int64(10)

In [6]:
import numpy as np
ar1 = np.array([1,2,3,4,5,6,7,8,9,10])
mins = ar1[0]
for a in ar1:
    if(a<mins):
        maxs = a
mins        

np.int64(1)

In [7]:
mins

np.int64(1)

In [9]:
# sum
import numpy as np
ar1 = np.array([1,2,3,4,5,6,7,8,9,10])
sums = 0
for a in ar1:
    sums =sums+a
sums

np.int64(55)

In [11]:
# len(count)
import numpy as np
ar1 = np.array([1,2,3,4,5,6,7,8,9,10])
count = 0
for a in ar1:
    count = count + 1
count

10

In [12]:
# Target value (how many position in array
ar = np.array([1,2,3,4,5,6,7,8,9,4,5,6,4])
target = 4
count = 0
for a in ar:
    if (a==target):
        count = count+1
count

3

In [5]:
# now we sort list in array
import numpy as np
ar = np.array([5,9,1,4,7,8,3,2,6])
li = list(ar)
sort = []
for a in range(0,len(ar)):
    sort.append(min(li))
    li.remove(min(li))
print(sort,end=" ")
sort


[1, 2, 3, 4, 5, 6, 7, 8, 9] 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
ar = np.array(sort)

In [31]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# third Day
# 2D array

In [23]:
math = ([[1,2,3],[4,5,6],[7,8,9]])
math

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
import numpy as np
math = np.array ([[1,2,3],[4,5,6],[7,8,9]])
math      
math.shape

(3, 3)

In [7]:
print("Row :",math.shape[0])
print("Column :",math.shape[1])

Row : 3
Column : 3


In [26]:
# how to work a matrix
for i in range(0,3):
    for j in range(0,3):
        print(math[i][j],end="  ")
    print()
    

1  2  3  
4  5  6  
7  8  9  


In [27]:
# how to add two matrix
math1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
math2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
math1,math2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [37]:
if((math1.shape[0]==math2.shape[0]) and (math1.shape[1]==math2.shape[1])):
    for i in range(0,math1.shape[0]):
        for j in range(0,math1.shape[1]):
            print(math1[i][j]+math2[i][j],end="     ")
        print()
else:
    print("Addition not possible")

2     4     6     
8     10     12     
14     16     18     


In [47]:
# Transpose matrix
math1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(0,math1.shape[0]):
    for j in range(0,math1.shape[1]):
        print(math1[j][i],end="  ")
    print()

1  4  7  
2  5  8  
3  6  9  


In [48]:
# Multiply two matrix
math1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
math2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
math3 = np.zeros_like(math1)
math1,math2,math3

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [49]:
for i in range(0,3):
    for j in range(0,3):
        val = 0
        for k in range(0,3):
            val = val + math1[i][k]*math2[k][j]
        math3[i][j] = val
        
            

In [53]:
math3

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# 4th Day
# some function

In [ ]:
# zeros
# ones
# zeros_like
# ones_like
# eye
# identity
# array
# arange
# linspace




import numpy as np
mat = np.zeros((3,3))
mat

In [60]:
mat = np.zeros((4,4),dtype=float)

In [63]:
mat

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
mat = np.zeros((4,4),dtype=float)

In [65]:
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
mat = np.zeros((4,4),dtype=int)

In [68]:
mat

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [71]:
mat = np.ones((3,3),dtype=int)
math

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [72]:
mat1 = np.zeros_like(math)

In [73]:
mat1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
math2 = np.ones_like(math1)
math2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [78]:
# eye function pass two arrgument and parfect array create by onece arrgument
mat = np.eye(3,4)
mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [81]:
# linspace can only one arrgument  pass(start,stop, how much value in range)
mt = np.linspace(3,10,10)
mt

array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [82]:
# Random Function 
# random (values between froms 0 to 1)
# random (0,1]
# randint (start,stop)

In [87]:
ar = np.random.random(10)          #(value between from 0 to 1) any five value create any time different value show
ar

array([0.96813253, 0.81408454, 0.76897771, 0.93554491, 0.78090474,
       0.42934962, 0.06292614, 0.6040812 , 0.79666919, 0.22429201])

In [90]:
ar = np.random.randint(1,10,3)
ar

array([2, 6, 7], dtype=int32)

# Now some practice Question

In [25]:
# wap to create an arra of 4X4 shapre of finbonacci value
n = int(input("enter a num :"))
x =1
y = 0
z = 1
while z<=n:
    print(z)
    x=y
    y=z
    z=x+y



enter a num : 10


1
1
2
3
5
8


In [9]:
# wap to create an arra of 4X4 shapre of finbonacci value
import numpy as np
def ficb(val1,val2,s1,s2):
    li =[]
    for i in range(0,s1):
        temp = []
        for j in range(0,s2):
            val3 = val1+val2
            temp.append(val3)
            val1= val2
            val2 = val3
        li.append(temp)
    return li
         

In [10]:
mat = np.array(ficb(0,1,4,4))


In [11]:
mat

array([[   1,    2,    3,    5],
       [   8,   13,   21,   34],
       [  55,   89,  144,  233],
       [ 377,  610,  987, 1597]])

In [40]:

 
# Function
# 41.check prime num
# def check_prime(num):
#     count=0
#     for a in range(1,num+1):
#         if(num%a==0):
#             count=count+1
#     if(count==2):
#         return "prime"
#     else:
#         return "not prime"

# print(check_prime(17))



# Numpy end
 